/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package face;

import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import util.ConectaBanco;

/**
 *
 * @author Fetkof
 */
public class Menu extends javax.swing.JFrame {
  ConectaBanco conecta = new ConectaBanco();
    ControlPerson cod = new ControlPerson();
    public Menu() {
        super("Dashboard | Group Project");
        initComponents();
         paint_table();
        cod.preencherTabela("SELECT * FROM person ORDER BY id", tabela);
       // Toolkit.getDefaultToolkit().getImage(javax.swing.JFrame.class.getResource("image.png"));


   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        txt_search = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        txt_id = new javax.swing.JTextField();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        txt_bGandGenotype = new javax.swing.JTextField();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        txt_nextOfKin = new javax.swing.JTextField();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        txt_phone = new javax.swing.JTextField();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        txt_address = new javax.swing.JTextField();
        kGradientPanel7 = new keeptoo.KGradientPanel();
        txt_name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        kGradientPanel10 = new keeptoo.KGradientPanel();
        kGradientPanel12 = new keeptoo.KGradientPanel();
        txt_github4 = new javax.swing.JTextField();
        kGradientPanel13 = new keeptoo.KGradientPanel();
        txt_github5 = new javax.swing.JTextField();
        kGradientPanel14 = new keeptoo.KGradientPanel();
        txt_github6 = new javax.swing.JTextField();
        kGradientPanel11 = new keeptoo.KGradientPanel();
        kGradientPanel15 = new keeptoo.KGradientPanel();
        txt_github7 = new javax.swing.JTextField();
        kGradientPanel16 = new keeptoo.KGradientPanel();
        txt_github8 = new javax.swing.JTextField();
        kGradientPanel17 = new keeptoo.KGradientPanel();
        txt_github9 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_allergies1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_extra = new javax.swing.JTextArea();
        sendMessage_btn = new keeptoo.KButton();
        kGradientPanel18 = new keeptoo.KGradientPanel();
        kGradientPanel19 = new keeptoo.KGradientPanel();
        txt_github10 = new javax.swing.JTextField();
        kGradientPanel20 = new keeptoo.KGradientPanel();
        txt_github11 = new javax.swing.JTextField();
        kGradientPanel21 = new keeptoo.KGradientPanel();
        txt_github12 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_allergies = new javax.swing.JTextArea();
        kGradientPanel22 = new keeptoo.KGradientPanel();
        kGradientPanel23 = new keeptoo.KGradientPanel();
        txt_github13 = new javax.swing.JTextField();
        kGradientPanel24 = new keeptoo.KGradientPanel();
        txt_github14 = new javax.swing.JTextField();
        kGradientPanel25 = new keeptoo.KGradientPanel();
        txt_github15 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_allergies3 = new javax.swing.JTextArea();
        kGradientPanel26 = new keeptoo.KGradientPanel();
        kGradientPanel27 = new keeptoo.KGradientPanel();
        txt_github16 = new javax.swing.JTextField();
        kGradientPanel28 = new keeptoo.KGradientPanel();
        txt_github17 = new javax.swing.JTextField();
        kGradientPanel29 = new keeptoo.KGradientPanel();
        txt_github18 = new javax.swing.JTextField();
        kGradientPanel30 = new keeptoo.KGradientPanel();
        kGradientPanel31 = new keeptoo.KGradientPanel();
        txt_github19 = new javax.swing.JTextField();
        kGradientPanel32 = new keeptoo.KGradientPanel();
        txt_github20 = new javax.swing.JTextField();
        kGradientPanel33 = new keeptoo.KGradientPanel();
        txt_github21 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt_allergies4 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txt_lastReport = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        s = new javax.swing.JLabel();
        txt_id_label = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txt_github = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(77, 158, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela.setFillsViewportHeight(true);
        tabela.setShowHorizontalLines(false);
        tabela.setShowVerticalLines(false);
        tabela.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tabelaFocusGained(evt);
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 500, 430));

        txt_search.setForeground(new java.awt.Color(169, 169, 169));
        txt_search.setText("Search here...");
        txt_search.setBorder(null);
        txt_search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_searchFocusLost(evt);
            }
        });
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 780, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1080, 10));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(118, 118, 118));
        jLabel3.setText("Home Address");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel4.setForeground(new java.awt.Color(118, 118, 118));
        jLabel4.setText("Next of Kin Details");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, -1));

        jLabel5.setForeground(new java.awt.Color(118, 118, 118));
        jLabel5.setText("Blood Group and Genotype");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLabel6.setForeground(new java.awt.Color(118, 118, 118));
        jLabel6.setText("Patient Id");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        jLabel7.setForeground(new java.awt.Color(118, 118, 118));
        jLabel7.setText("Allergies and Existing Conditions");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel8.setForeground(new java.awt.Color(118, 118, 118));
        jLabel8.setText("Phone");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        kGradientPanel2.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkFillBackground(false);
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_id.setEditable(false);
        txt_id.setBorder(null);
        txt_id.setOpaque(false);
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        kGradientPanel2.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 30));

        jPanel2.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 180, 30));

        kGradientPanel3.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel3.setkFillBackground(false);
        kGradientPanel3.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_bGandGenotype.setBorder(null);
        txt_bGandGenotype.setOpaque(false);
        kGradientPanel3.add(txt_bGandGenotype, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 30));

        jPanel2.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 180, 30));

        kGradientPanel4.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel4.setkFillBackground(false);
        kGradientPanel4.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nextOfKin.setBorder(null);
        txt_nextOfKin.setOpaque(false);
        kGradientPanel4.add(txt_nextOfKin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 30));

        jPanel2.add(kGradientPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, 30));

        kGradientPanel5.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel5.setkFillBackground(false);
        kGradientPanel5.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_phone.setBorder(null);
        txt_phone.setOpaque(false);
        kGradientPanel5.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 30));

        jPanel2.add(kGradientPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 180, 30));

        kGradientPanel6.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel6.setkFillBackground(false);
        kGradientPanel6.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_address.setBorder(null);
        txt_address.setOpaque(false);
        kGradientPanel6.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 30));

        jPanel2.add(kGradientPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 180, 30));

        kGradientPanel7.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel7.setkFillBackground(false);
        kGradientPanel7.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_name.setBorder(null);
        txt_name.setOpaque(false);
        kGradientPanel7.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 30));

        jPanel2.add(kGradientPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, 30));

        jLabel9.setForeground(new java.awt.Color(118, 118, 118));
        jLabel9.setText("First Name");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel11.setForeground(new java.awt.Color(118, 118, 118));
        jLabel11.setText("Last Appointment- Date & Report");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel15.setForeground(new java.awt.Color(118, 118, 118));
        jLabel15.setText("Last Appointment- Date & Report");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        kGradientPanel10.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel10.setkFillBackground(false);
        kGradientPanel10.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel12.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel12.setkFillBackground(false);
        kGradientPanel12.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_github4.setBorder(null);
        txt_github4.setOpaque(false);
        kGradientPanel12.add(txt_github4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 90));

        kGradientPanel10.add(kGradientPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, 90));

        kGradientPanel13.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel13.setkFillBackground(false);
        kGradientPanel13.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_github5.setBorder(null);
        txt_github5.setOpaque(false);
        kGradientPanel13.add(txt_github5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 90));

        kGradientPanel14.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel14.setkFillBackground(false);
        kGradientPanel14.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_github6.setBorder(null);
        txt_github6.setOpaque(false);
        kGradientPanel14.add(txt_github6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 90));

        kGradientPanel13.add(kGradientPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, 90));

        kGradientPanel10.add(kGradientPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, 90));

        kGradientPanel11.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel11.setkFillBackground(false);
        kGradientPanel11.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel15.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel15.setkFillBackground(false);
        kGradientPanel15.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_github7.setBorder(null);
        txt_github7.setOpaque(false);
        kGradientPanel15.add(txt_github7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 90));

        kGradientPanel11.add(kGradientPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, 90));

        kGradientPanel16.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel16.setkFillBackground(false);
        kGradientPanel16.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_github8.setBorder(null);
        txt_github8.setOpaque(false);
        kGradientPanel16.add(txt_github8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 90));

        kGradientPanel17.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel17.setkFillBackground(false);
        kGradientPanel17.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_github9.setBorder(null);
        txt_github9.setOpaque(false);
        kGradientPanel17.add(txt_github9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 90));

        kGradientPanel16.add(kGradientPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, 90));

        kGradientPanel11.add(kGradientPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, 90));

        txt_allergies1.setColumns(20);
        txt_allergies1.setRows(5);
        txt_allergies1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        jScrollPane3.setViewportView(txt_allergies1);

        kGradientPanel11.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 80));

        kGradientPanel10.add(kGradientPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 170, 90));

        txt_extra.setColumns(20);
        txt_extra.setRows(5);
        txt_extra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        jScrollPane2.setViewportView(txt_extra);

        kGradientPanel10.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 80));

        jPanel2.add(kGradientPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 170, 90));

        sendMessage_btn.setText("Save");
        sendMessage_btn.setkAllowTab(false);
        sendMessage_btn.setkEndColor(new java.awt.Color(0, 102, 204));
        sendMessage_btn.setkHoverEndColor(new java.awt.Color(51, 153, 255));
        sendMessage_btn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        sendMessage_btn.setkHoverStartColor(new java.awt.Color(51, 153, 255));
        sendMessage_btn.setkPressedColor(new java.awt.Color(204, 204, 204));
        sendMessage_btn.setkStartColor(new java.awt.Color(0, 102, 255));
        sendMessage_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessage_btnActionPerformed(evt);
            }
        });
        jPanel2.add(sendMessage_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 390, 30));
        sendMessage_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        kGradientPanel18.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel18.setkFillBackground(false);
        kGradientPanel18.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel19.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel19.setkFillBackground(false);
        kGradientPanel19.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_github10.setBorder(null);
        txt_github10.setOpaque(false);
        kGradientPanel19.add(txt_github10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 90));

        kGradientPanel18.add(kGradientPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, 90));

        kGradientPanel20.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel20.setkFillBackground(false);
        kGradientPanel20.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_github11.setBorder(null);
        txt_github11.setOpaque(false);
        kGradientPanel20.add(txt_github11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 90));

        kGradientPanel21.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel21.setkFillBackground(false);
        kGradientPanel21.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_github12.setBorder(null);
        txt_github12.setOpaque(false);
        kGradientPanel21.add(txt_github12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 90));

        kGradientPanel20.add(kGradientPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, 90));

        kGradientPanel18.add(kGradientPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, 90));

        txt_allergies.setColumns(20);
        txt_allergies.setRows(5);
        txt_allergies.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        jScrollPane4.setViewportView(txt_allergies);

        kGradientPanel18.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 80));

        kGradientPanel22.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel22.setkFillBackground(false);
        kGradientPanel22.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel23.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel23.setkFillBackground(false);
        kGradientPanel23.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_github13.setBorder(null);
        txt_github13.setOpaque(false);
        kGradientPanel23.add(txt_github13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 90));

        kGradientPanel22.add(kGradientPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, 90));

        kGradientPanel24.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel24.setkFillBackground(false);
        kGradientPanel24.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_github14.setBorder(null);
        txt_github14.setOpaque(false);
        kGradientPanel24.add(txt_github14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 90));

        kGradientPanel25.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel25.setkFillBackground(false);
        kGradientPanel25.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_github15.setBorder(null);
        txt_github15.setOpaque(false);
        kGradientPanel25.add(txt_github15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 90));

        kGradientPanel24.add(kGradientPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, 90));

        kGradientPanel22.add(kGradientPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, 90));

        txt_allergies3.setColumns(20);
        txt_allergies3.setRows(5);
        txt_allergies3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        jScrollPane5.setViewportView(txt_allergies3);

        kGradientPanel22.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 80));

        kGradientPanel18.add(kGradientPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 170, 90));

        jPanel2.add(kGradientPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 170, 90));

        kGradientPanel26.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel26.setkFillBackground(false);
        kGradientPanel26.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel27.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel27.setkFillBackground(false);
        kGradientPanel27.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_github16.setBorder(null);
        txt_github16.setOpaque(false);
        kGradientPanel27.add(txt_github16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 90));

        kGradientPanel26.add(kGradientPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, 90));

        kGradientPanel28.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel28.setkFillBackground(false);
        kGradientPanel28.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_github17.setBorder(null);
        txt_github17.setOpaque(false);
        kGradientPanel28.add(txt_github17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 90));

        kGradientPanel29.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel29.setkFillBackground(false);
        kGradientPanel29.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_github18.setBorder(null);
        txt_github18.setOpaque(false);
        kGradientPanel29.add(txt_github18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 90));

        kGradientPanel28.add(kGradientPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, 90));

        kGradientPanel26.add(kGradientPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, 90));

        kGradientPanel30.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel30.setkFillBackground(false);
        kGradientPanel30.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel31.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel31.setkFillBackground(false);
        kGradientPanel31.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_github19.setBorder(null);
        txt_github19.setOpaque(false);
        kGradientPanel31.add(txt_github19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 90));

        kGradientPanel30.add(kGradientPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, 90));

        kGradientPanel32.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel32.setkFillBackground(false);
        kGradientPanel32.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_github20.setBorder(null);
        txt_github20.setOpaque(false);
        kGradientPanel32.add(txt_github20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 90));

        kGradientPanel33.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel33.setkFillBackground(false);
        kGradientPanel33.setkStartColor(new java.awt.Color(0, 123, 255));
        kGradientPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_github21.setBorder(null);
        txt_github21.setOpaque(false);
        kGradientPanel33.add(txt_github21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 90));

        kGradientPanel32.add(kGradientPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, 90));

        kGradientPanel30.add(kGradientPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, 90));

        txt_allergies4.setColumns(20);
        txt_allergies4.setRows(5);
        txt_allergies4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        jScrollPane6.setViewportView(txt_allergies4);

        kGradientPanel30.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 80));

        kGradientPanel26.add(kGradientPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 170, 90));

        txt_lastReport.setColumns(20);
        txt_lastReport.setRows(5);
        txt_lastReport.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        jScrollPane7.setViewportView(txt_lastReport);

        kGradientPanel26.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 80));

        jPanel2.add(kGradientPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 170, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 580, 330));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(100, 100, 100));
        jLabel13.setText("Records");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        s.setBackground(new java.awt.Color(90, 68, 193));
        s.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        s.setForeground(new java.awt.Color(255, 255, 255));
        s.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 340, 40));

        txt_id_label.setBackground(new java.awt.Color(132, 242, 145));
        txt_id_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_id_label.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(txt_id_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 40, 40));

        jLabel14.setBackground(new java.awt.Color(90, 68, 193));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("ID Finger");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 970, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(135, 135, 136));
        jLabel12.setText("Patient Information");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, -1, -1));
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txt_github.setBorder(null);
        txt_github.setOpaque(false);
        txt_github.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_githubActionPerformed(evt);
            }
        });
        jPanel1.add(txt_github, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 160, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 550));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Add_User_Group_Woman_Man_25px.png"))); // NOI18N
        jMenu1.setText("Register Patient");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Filled_Circle_15px.png"))); // NOI18N
        jMenu2.setText("Verify Patient");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabelaFocusGained
        txt_search.setForeground(new java.awt.Color(169, 169, 169));
        txt_search.setText("Search here...");
    }//GEN-LAST:event_tabelaFocusGained

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        conecta.conexao();
        try {
            String nome = "" + tabela.getValueAt(tabela.getSelectedRow(), 1);
            conecta.executaSQL("SELECT * FROM person WHERE id = '" + nome + "'");
            conecta.rs.first();
            id = conecta.rs.getInt("id");
            txt_id.setText(String.valueOf(id));
            txt_name.setText(String.valueOf(conecta.rs.getString("first_name")));
         //   txt_lastname.setText(String.valueOf(conecta.rs.getString("last_name")));
            txt_address.setText(String.valueOf(conecta.rs.getString("address")));
            txt_phone.setText(String.valueOf(conecta.rs.getString("phone_number")));
            txt_nextOfKin.setText(String.valueOf(conecta.rs.getString("next_of_kin")));
            txt_bGandGenotype.setText(String.valueOf(conecta.rs.getString("blood_group_genotype")));
            txt_extra.setText(String.valueOf(conecta.rs.getString("extra")));
             txt_allergies.setText(String.valueOf(conecta.rs.getString("allergies")));
              txt_lastReport.setText(String.valueOf(conecta.rs.getString("lastreport")));
            txt_id.setText(String.valueOf(id));
         
        } catch (SQLException s) {
            //JOptionPane.showMessageDialog(rootPane, "Erro ao Selecionar os Dados!\nErro:" + s);
        }
        conecta.desconecta();
    }//GEN-LAST:event_tabelaMouseClicked

    private void tabelaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseReleased
        if (evt.isPopupTrigger()) {//Se o mouse foi clicado com o botão de PopupMenu default do sistema operacional em uso
            jPopupMenu1.show(tabela, evt.getX(), evt.getY()); //p é o JPopupMenu, t é a tabela, e.getX() recupera a posição horizontal do mouse e e.getY() recupera a posição vertical.
        }
    }//GEN-LAST:event_tabelaMouseReleased
 int id;
    private void txt_searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_searchFocusGained
        txt_search.setText("");
        txt_search.setForeground(new java.awt.Color(32, 32, 32));
    }//GEN-LAST:event_txt_searchFocusGained

    private void txt_searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_searchFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchFocusLost

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        cod.preencherTabela("SELECT * FROM person WHERE first_name LIKE '%" + txt_search.getText() + "%' OR last_name LIKE '%" + txt_search.getText() + "%' OR address LIKE '%" + txt_search.getText() + "%' ORDER BY id", tabela);
    }//GEN-LAST:event_txt_searchKeyReleased

    private void sendMessage_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessage_btnActionPerformed
        ModelPerson mod = new ModelPerson();
        mod.setId(id);
        mod.setFirst_name(txt_name.getText());
       // mod.setLast_name(txt_lastname.getText());
        mod.setPhone(txt_phone.getText());
        mod.setAddress(txt_address.getText());
        mod.setnextOfKin(txt_nextOfKin.getText());
        mod.setallergies(txt_allergies.getText());
        mod.setlastReport(txt_lastReport.getText());
         mod.setbGandGenotype(txt_bGandGenotype.getText());
         mod.setExtra(txt_extra.getText());
        cod.update(mod, id);
        JOptionPane.showMessageDialog(null, "Updated Successfully");
    }//GEN-LAST:event_sendMessage_btnActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    JOptionPane jop = new JOptionPane();
jop.setMessageType(JOptionPane.PLAIN_MESSAGE);
jop.setMessage("Please Wait..");
final JDialog dialog = jop.createDialog(null, "Message");

// Set a 2 second timer
new Thread(new Runnable() {
    @Override
    public void run() {
        try {
            Thread.sleep(1500);
        } catch (Exception e) {
        }
        dialog.dispose();
    }

}).start();

dialog.setVisible(true);  

        RegisterFace reg = new RegisterFace();
        reg.setVisible(true);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        JOptionPane jop = new JOptionPane();
jop.setMessageType(JOptionPane.PLAIN_MESSAGE);
jop.setMessage("Please Wait..");
final JDialog dialog = jop.createDialog(null, "Message");

// Set a 2 second timer
new Thread(new Runnable() {
    @Override
    public void run() {
        try {
            Thread.sleep(1500);
        } catch (Exception e) {
        }
        dialog.dispose();
    }

}).start();

dialog.setVisible(true);  


        RegisterFace reg = new RegisterFace();
        reg.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
// TODO add your handling code here:
JOptionPane jop = new JOptionPane();
jop.setMessageType(JOptionPane.PLAIN_MESSAGE);
jop.setMessage("Please Wait..");
final JDialog dialog = jop.createDialog(null, "Message");

// Set a 2 second timer
new Thread(new Runnable() {
    @Override
    public void run() {
        try {
            Thread.sleep(1500);
        } catch (Exception e) {
        }
        dialog.dispose();
    }

}).start();

dialog.setVisible(true);  
      
        RecognizeFace reg = new RecognizeFace();
        reg.setVisible(true);
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        
JOptionPane jop = new JOptionPane();
jop.setMessageType(JOptionPane.PLAIN_MESSAGE);
jop.setMessage("Please Wait..");
final JDialog dialog = jop.createDialog(null, "Message");

// Set a 2 second timer
new Thread(new Runnable() {
    @Override
    public void run() {
        try {
            Thread.sleep(1500);
        } catch (Exception e) {
        }
        dialog.dispose();
    }

}).start();

dialog.setVisible(true);  
       RecognizeFace reg = new RecognizeFace();
        reg.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void txt_githubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_githubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_githubActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private keeptoo.KGradientPanel kGradientPanel10;
    private keeptoo.KGradientPanel kGradientPanel11;
    private keeptoo.KGradientPanel kGradientPanel12;
    private keeptoo.KGradientPanel kGradientPanel13;
    private keeptoo.KGradientPanel kGradientPanel14;
    private keeptoo.KGradientPanel kGradientPanel15;
    private keeptoo.KGradientPanel kGradientPanel16;
    private keeptoo.KGradientPanel kGradientPanel17;
    private keeptoo.KGradientPanel kGradientPanel18;
    private keeptoo.KGradientPanel kGradientPanel19;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel20;
    private keeptoo.KGradientPanel kGradientPanel21;
    private keeptoo.KGradientPanel kGradientPanel22;
    private keeptoo.KGradientPanel kGradientPanel23;
    private keeptoo.KGradientPanel kGradientPanel24;
    private keeptoo.KGradientPanel kGradientPanel25;
    private keeptoo.KGradientPanel kGradientPanel26;
    private keeptoo.KGradientPanel kGradientPanel27;
    private keeptoo.KGradientPanel kGradientPanel28;
    private keeptoo.KGradientPanel kGradientPanel29;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel30;
    private keeptoo.KGradientPanel kGradientPanel31;
    private keeptoo.KGradientPanel kGradientPanel32;
    private keeptoo.KGradientPanel kGradientPanel33;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel6;
    private keeptoo.KGradientPanel kGradientPanel7;
    private javax.swing.JLabel s;
    private keeptoo.KButton sendMessage_btn;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextArea txt_allergies;
    private javax.swing.JTextArea txt_allergies1;
    private javax.swing.JTextArea txt_allergies3;
    private javax.swing.JTextArea txt_allergies4;
    private javax.swing.JTextField txt_bGandGenotype;
    private javax.swing.JTextArea txt_extra;
    private javax.swing.JTextField txt_github;
    private javax.swing.JTextField txt_github10;
    private javax.swing.JTextField txt_github11;
    private javax.swing.JTextField txt_github12;
    private javax.swing.JTextField txt_github13;
    private javax.swing.JTextField txt_github14;
    private javax.swing.JTextField txt_github15;
    private javax.swing.JTextField txt_github16;
    private javax.swing.JTextField txt_github17;
    private javax.swing.JTextField txt_github18;
    private javax.swing.JTextField txt_github19;
    private javax.swing.JTextField txt_github20;
    private javax.swing.JTextField txt_github21;
    private javax.swing.JTextField txt_github4;
    private javax.swing.JTextField txt_github5;
    private javax.swing.JTextField txt_github6;
    private javax.swing.JTextField txt_github7;
    private javax.swing.JTextField txt_github8;
    private javax.swing.JTextField txt_github9;
    private javax.swing.JTextField txt_id;
    private javax.swing.JLabel txt_id_label;
    private javax.swing.JTextArea txt_lastReport;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_nextOfKin;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables

    private void paint_table() {
   jScrollPane1.getViewport().setBackground(Color.WHITE);
        tabela.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tabela.getTableHeader().setOpaque(false);
        tabela.getTableHeader().setBackground(new Color(60, 127, 177));
        tabela.getTableHeader().setForeground(new Color(255, 255, 255));
        tabela.setRowHeight(50); }
}
